name: Check Markdown links
## uing - uses: rojopolis/spellcheck-github-actions@0.14.0

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      name: "check md links"
      with:
        config-file: '.md-config.json'
