---
title: md-linkcheck.yml
---

# {{data.title}}

name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      name: "check md links"
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'no'
        config-file: '.github/md-linkcheck.json'
