name: Check for spelling errors (manual)
## using - uses: rojopolis/spellcheck-github-actions@0.14.0

on:
  workflow_dispatch:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      name: check-out

    - uses: rojopolis/spellcheck-github-actions@0.16.0
      name: check spelling
      continue-on-error: true
      with:
        config_path: .github/spellcheck-config.yml 
      # uses: UnicornGlobal/spellcheck-github-actions@0.4.0
